Rewrite phpbb-merge in perl

diff --git a/phpbb-merge b/phpbb-merge
--- a/phpbb-merge
+++ b/phpbb-merge
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/usr/bin/env perl
 
 # Usage:
 #
@@ -12,64 +12,77 @@
 #
 # phpbb-merge -d
 
-set -e
+use strict;
+use warnings;
 
-branch=
-forward=false
+use Getopt::Long;
 
-if test "$1" = -d; then
-	if test -f $HOME/.phpbb-merge-state; then
-		# freebsd's /bin/sh creates a new environment when
-		# reading in a pipe, which causes echo foo |read bar
-		# to effectively discard the read operation.
-		# use awk to work around this
-		pr=`awk '{print $2}' <$HOME/.phpbb-merge-state`
-		branch=`awk '{print $3}' <$HOME/.phpbb-merge-state`
-		forward=true
-	fi
-fi
+my ($branch, $pr, $target, $forward);
 
-if test -z "$branch"; then
-	branch="$1"
-	pr="$2"
-	target="$3"
-fi
+$forward = 0;
 
-if test -z "$pr"; then
-	echo "Usage: `basename $0` branch PR" 1>&2
-	echo "       `basename $0` -d" 1>&2
-	exit 5
-fi
+my $home = $ENV{'HOME'};
+my $state_file = "$home/.phpbb-merge-state";
 
-if test "$target" = o -o "$target" = olympus; then
-	target=develop-olympus
-fi
+my $develop = '';
 
-if test -z "$target"; then
-	target=develop
-fi
+GetOptions('develop' => \$develop);
 
-echo "Merging $branch into $target for PR #$pr"
+if ($develop) {
+    if (-e $state_file) {
+        open FH, "<$state_file" || die "Could not open $state_file: $!";
+        my $contents = <FH>;
+        close FH;
+        ($forward, $pr, $branch) = split ' ', $contents;
+        $forward = 1;
+    }
+}
 
-current_branch=`git branch |grep '^\*' |awk '{print $2}'`
+if (!$branch) {
+    ($branch, $pr, $target) = @ARGV;
+}
 
-if test "$current_branch" != "$target"; then
-	git checkout "$target"
-fi
+if (!$pr) {
+    print "Usage: phpbb-merge branch PR\n";
+    print "       phpbb-merge -d\n";
+    exit 5;
+}
 
-if ! $forward; then
-	echo "$branch $pr $target" >$HOME/.phpbb-merge-state
-fi
+if ($target and $target eq 'o' || $target eq 'olympus') {
+    $target = 'develop-olympus';
+}
 
-git merge --no-ff "$branch"
+if (!$target) {
+    $target = 'develop';
+}
 
-if $forward; then
-	git filter-branch  --msg-filter \
-		"sed -e 's/^Merge branch/Merge PR #$pr branch/'" \
-		-f -- --max-count=1 HEAD
+print "Merging $branch into $target for PR #$pr\n";
 
-	rm -f $HOME/.phpbb-merge-state
-else
-	git filter-branch  --msg-filter "sed -e s/remote-tracking/'PR #$pr'/" \
-		-f -- --max-count=1 HEAD
-fi
+my $current_branch = `git branch |grep '^\*' |awk '{print \$2}'`;
+
+if ($current_branch ne $target) {
+    print `git checkout "$target"`;
+}
+
+if (!$forward) {
+    open FH, ">$state_file" or die "Could not open state file: $!";
+    print FH "$branch $pr $target";
+    close FH;
+}
+
+print `git merge --no-ff "$branch"`;
+
+my $sed_cmd;
+if ($forward) {
+    $sed_cmd = qq.sed -e 's/^Merge branch/Merge PR #$pr branch/'.;
+} else {
+    $sed_cmd = qq.sed -e s/remote-tracking/'PR #$pr'/.;
+}
+
+print `git filter-branch  --msg-filter "$sed_cmd" -f -- --max-count=1 HEAD`;
+
+if ($forward) {
+    if (-e $state_file) {
+        unlink($state_file);
+    }
+}
